-- CreateEnum
CREATE TYPE "WorkflowAction" AS ENUM ('CREATE', 'SUBMIT', 'APPROVE_DEPT', 'REJECT_DEPT', 'APPROVE_ARCHIVE', 'REJECT_ARCHIVE', 'RESUBMIT', 'ARCHIVE', 'COMMENT');

-- AlterEnum: nuevos estados (deben confirmarse antes de usarse como DEFAULT)
ALTER TYPE "DocumentStatus" ADD VALUE 'DRAFT';
ALTER TYPE "DocumentStatus" ADD VALUE 'PENDING_REVIEW';
ALTER TYPE "DocumentStatus" ADD VALUE 'IN_REVIEW_DEPT';
ALTER TYPE "DocumentStatus" ADD VALUE 'REJECTED_DEPT';
ALTER TYPE "DocumentStatus" ADD VALUE 'APPROVED_DEPT';
ALTER TYPE "DocumentStatus" ADD VALUE 'IN_REVIEW_ARCHIVE';
ALTER TYPE "DocumentStatus" ADD VALUE 'REJECTED_ARCHIVE';
ALTER TYPE "DocumentStatus" ADD VALUE 'ARCHIVED';
ALTER TYPE "DocumentStatus" ADD VALUE 'TRANSFERRED';
ALTER TYPE "DocumentStatus" ADD VALUE 'HISTORICAL';

-- AlterEnum
ALTER TYPE "RoleCode" ADD VALUE 'DEPT_WORKER';
