-- Location levels
ALTER TYPE "LocationLevel" ADD VALUE IF NOT EXISTS 'BUILDING';
ALTER TYPE "LocationLevel" ADD VALUE IF NOT EXISTS 'FLOOR';
ALTER TYPE "LocationLevel" ADD VALUE IF NOT EXISTS 'RACK';
